{{/*
#   Copyright 2022 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
*/}}

{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "gitlab.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gitlab.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gitlab.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gitlab.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: remove-data
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.initContainerImage.repository }}:{{ .Values.initContainerImage.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh", "-c"]
          args:
            - |
              {{- if .Values.persistence.reinstall }}
              echo "Removing data for database..."
              rm -rf {{ .Values.persistence.mountPath.dataDir }}/*
              {{- else }}
              echo "Leave data for database."
              {{- end }}
          volumeMounts:
            - name: volume-{{ template "gitlab.name" . }}-data
              mountPath: {{ .Values.persistence.mountPath.dataDir }}
      containers:
        - name: {{ template "gitlab.name" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: platform-params-pf-global
                key: TZ
          - name: GITLAB_PROTOCOL
            valueFrom:
              configMapKeyRef:
                name: platform-params-pf-gitlab
                key: GITLAB_PROTOCOL
          - name: GITLAB_HOST
            valueFrom:
              configMapKeyRef:
                name: platform-params-pf-gitlab
                key: GITLAB_HOST
          - name: GITLAB_PORT
            valueFrom:
              configMapKeyRef:
                name: platform-params-pf-gitlab
                key: GITLAB_PORT
          - name: GITLAB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: platform-secret-pf-gitlab
                key: GITLAB_ROOT_PASSWORD
          - name: GITLAB_ROOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: platform-secret-pf-gitlab
                key: GITLAB_ROOT_TOKEN
          {{- range $config, $value := .Values.extraEnv }}
          - name: {{ $config }}
            valueFrom:
              configMapKeyRef:
                name: params-{{ template "gitlab.name" $ }}
                key: {{ $config }}
          {{- end }}
          volumeMounts:
            - name: volume-{{ template "gitlab.name" . }}-log
              mountPath: {{ .Values.persistence.mountPath.logDir }}
            - name: volume-{{ template "gitlab.name" . }}-data
              mountPath: {{ .Values.persistence.mountPath.dataDir }}
          ports:
            - name: port-gitlab
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            # tcpSocket:
            #   port: {{ .Values.service.port }}
            httpGet:
              path: /-/liveness
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 1000
          readinessProbe:
            # tcpSocket:
            #   port: {{ .Values.service.port }}
            httpGet:
              path: /-/readiness
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 1000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: volume-{{ template "gitlab.name" . }}-log
          emptyDir: {}
        - name: volume-{{ template "gitlab.name" . }}-data
          {{- if and .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: pvc-{{ template "gitlab.name" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}